// flow-typed signature: bcbf6b71852ab0f8ddf87d46946f5148
// flow-typed version: <<STUB>>/ballboy_v^1.1.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ballboy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ballboy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ballboy/jest.config' {
  declare module.exports: any;
}

declare module 'ballboy/lib/index' {
  declare module.exports: any;
}

declare module 'ballboy/src/__mocks__/constans' {
  declare module.exports: any;
}

declare module 'ballboy/src/__mocks__/fs' {
  declare module.exports: any;
}

declare module 'ballboy/src/__mocks__/http' {
  declare module.exports: any;
}

declare module 'ballboy/src/__mocks__/https' {
  declare module.exports: any;
}

declare module 'ballboy/src/bellboy.test' {
  declare module.exports: any;
}

declare module 'ballboy/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ballboy/jest.config.js' {
  declare module.exports: $Exports<'ballboy/jest.config'>;
}
declare module 'ballboy/lib/index.js' {
  declare module.exports: $Exports<'ballboy/lib/index'>;
}
declare module 'ballboy/src/__mocks__/constans.js' {
  declare module.exports: $Exports<'ballboy/src/__mocks__/constans'>;
}
declare module 'ballboy/src/__mocks__/fs.js' {
  declare module.exports: $Exports<'ballboy/src/__mocks__/fs'>;
}
declare module 'ballboy/src/__mocks__/http.js' {
  declare module.exports: $Exports<'ballboy/src/__mocks__/http'>;
}
declare module 'ballboy/src/__mocks__/https.js' {
  declare module.exports: $Exports<'ballboy/src/__mocks__/https'>;
}
declare module 'ballboy/src/bellboy.test.js' {
  declare module.exports: $Exports<'ballboy/src/bellboy.test'>;
}
declare module 'ballboy/src/index.js' {
  declare module.exports: $Exports<'ballboy/src/index'>;
}
