// flow-typed signature: ed6298bc822a7490339cfcd68741655e
// flow-typed version: <<STUB>>/joi_v^14.0.6/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'joi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'joi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'joi/lib/cast' {
  declare module.exports: any;
}

declare module 'joi/lib/errors' {
  declare module.exports: any;
}

declare module 'joi/lib/index' {
  declare module.exports: any;
}

declare module 'joi/lib/language' {
  declare module.exports: any;
}

declare module 'joi/lib/ref' {
  declare module.exports: any;
}

declare module 'joi/lib/schemas' {
  declare module.exports: any;
}

declare module 'joi/lib/set' {
  declare module.exports: any;
}

declare module 'joi/lib/types/alternatives/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/any/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/any/settings' {
  declare module.exports: any;
}

declare module 'joi/lib/types/array/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/binary/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/boolean/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/date/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/func/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/lazy/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/number/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/object/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/state' {
  declare module.exports: any;
}

declare module 'joi/lib/types/string/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/string/ip' {
  declare module.exports: any;
}

declare module 'joi/lib/types/string/rfc3986' {
  declare module.exports: any;
}

declare module 'joi/lib/types/string/uri' {
  declare module.exports: any;
}

declare module 'joi/lib/types/symbol/index' {
  declare module.exports: any;
}

declare module 'joi/lib/types/symbols' {
  declare module.exports: any;
}

// Filename aliases
declare module 'joi/lib/cast.js' {
  declare module.exports: $Exports<'joi/lib/cast'>;
}
declare module 'joi/lib/errors.js' {
  declare module.exports: $Exports<'joi/lib/errors'>;
}
declare module 'joi/lib/index.js' {
  declare module.exports: $Exports<'joi/lib/index'>;
}
declare module 'joi/lib/language.js' {
  declare module.exports: $Exports<'joi/lib/language'>;
}
declare module 'joi/lib/ref.js' {
  declare module.exports: $Exports<'joi/lib/ref'>;
}
declare module 'joi/lib/schemas.js' {
  declare module.exports: $Exports<'joi/lib/schemas'>;
}
declare module 'joi/lib/set.js' {
  declare module.exports: $Exports<'joi/lib/set'>;
}
declare module 'joi/lib/types/alternatives/index.js' {
  declare module.exports: $Exports<'joi/lib/types/alternatives/index'>;
}
declare module 'joi/lib/types/any/index.js' {
  declare module.exports: $Exports<'joi/lib/types/any/index'>;
}
declare module 'joi/lib/types/any/settings.js' {
  declare module.exports: $Exports<'joi/lib/types/any/settings'>;
}
declare module 'joi/lib/types/array/index.js' {
  declare module.exports: $Exports<'joi/lib/types/array/index'>;
}
declare module 'joi/lib/types/binary/index.js' {
  declare module.exports: $Exports<'joi/lib/types/binary/index'>;
}
declare module 'joi/lib/types/boolean/index.js' {
  declare module.exports: $Exports<'joi/lib/types/boolean/index'>;
}
declare module 'joi/lib/types/date/index.js' {
  declare module.exports: $Exports<'joi/lib/types/date/index'>;
}
declare module 'joi/lib/types/func/index.js' {
  declare module.exports: $Exports<'joi/lib/types/func/index'>;
}
declare module 'joi/lib/types/lazy/index.js' {
  declare module.exports: $Exports<'joi/lib/types/lazy/index'>;
}
declare module 'joi/lib/types/number/index.js' {
  declare module.exports: $Exports<'joi/lib/types/number/index'>;
}
declare module 'joi/lib/types/object/index.js' {
  declare module.exports: $Exports<'joi/lib/types/object/index'>;
}
declare module 'joi/lib/types/state.js' {
  declare module.exports: $Exports<'joi/lib/types/state'>;
}
declare module 'joi/lib/types/string/index.js' {
  declare module.exports: $Exports<'joi/lib/types/string/index'>;
}
declare module 'joi/lib/types/string/ip.js' {
  declare module.exports: $Exports<'joi/lib/types/string/ip'>;
}
declare module 'joi/lib/types/string/rfc3986.js' {
  declare module.exports: $Exports<'joi/lib/types/string/rfc3986'>;
}
declare module 'joi/lib/types/string/uri.js' {
  declare module.exports: $Exports<'joi/lib/types/string/uri'>;
}
declare module 'joi/lib/types/symbol/index.js' {
  declare module.exports: $Exports<'joi/lib/types/symbol/index'>;
}
declare module 'joi/lib/types/symbols.js' {
  declare module.exports: $Exports<'joi/lib/types/symbols'>;
}
