// flow-typed signature: 828b85e63789c7e87d82359117d9aaf2
// flow-typed version: <<STUB>>/openapi3-flowtype-definition_v^0.3.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openapi3-flowtype-definition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'openapi3-flowtype-definition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openapi3-flowtype-definition/lib/OpenAPI' {
  declare module.exports: any;
}

declare module 'openapi3-flowtype-definition/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openapi3-flowtype-definition/lib/OpenAPI.js' {
  declare module.exports: $Exports<'openapi3-flowtype-definition/lib/OpenAPI'>;
}
declare module 'openapi3-flowtype-definition/src/index.js' {
  declare module.exports: $Exports<'openapi3-flowtype-definition/src/index'>;
}
