// flow-typed signature: 0574d49f2d626b671de88cf9df660169
// flow-typed version: <<STUB>>/random_v^2.0.12/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random/dist/distributions/bates' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/bernoulli' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/binomial' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/exponential' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/geometric' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/irwin-hall' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/log-normal' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/normal' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/pareto' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/poisson' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/uniform-boolean' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/uniform-int' {
  declare module.exports: any;
}

declare module 'random/dist/distributions/uniform' {
  declare module.exports: any;
}

declare module 'random/dist/generators/function' {
  declare module.exports: any;
}

declare module 'random/dist/generators/math-random' {
  declare module.exports: any;
}

declare module 'random/dist/generators/xor128' {
  declare module.exports: any;
}

declare module 'random/dist/random' {
  declare module.exports: any;
}

declare module 'random/dist/rng-factory' {
  declare module.exports: any;
}

declare module 'random/dist/rng' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random/dist/distributions/bates.js' {
  declare module.exports: $Exports<'random/dist/distributions/bates'>;
}
declare module 'random/dist/distributions/bernoulli.js' {
  declare module.exports: $Exports<'random/dist/distributions/bernoulli'>;
}
declare module 'random/dist/distributions/binomial.js' {
  declare module.exports: $Exports<'random/dist/distributions/binomial'>;
}
declare module 'random/dist/distributions/exponential.js' {
  declare module.exports: $Exports<'random/dist/distributions/exponential'>;
}
declare module 'random/dist/distributions/geometric.js' {
  declare module.exports: $Exports<'random/dist/distributions/geometric'>;
}
declare module 'random/dist/distributions/irwin-hall.js' {
  declare module.exports: $Exports<'random/dist/distributions/irwin-hall'>;
}
declare module 'random/dist/distributions/log-normal.js' {
  declare module.exports: $Exports<'random/dist/distributions/log-normal'>;
}
declare module 'random/dist/distributions/normal.js' {
  declare module.exports: $Exports<'random/dist/distributions/normal'>;
}
declare module 'random/dist/distributions/pareto.js' {
  declare module.exports: $Exports<'random/dist/distributions/pareto'>;
}
declare module 'random/dist/distributions/poisson.js' {
  declare module.exports: $Exports<'random/dist/distributions/poisson'>;
}
declare module 'random/dist/distributions/uniform-boolean.js' {
  declare module.exports: $Exports<'random/dist/distributions/uniform-boolean'>;
}
declare module 'random/dist/distributions/uniform-int.js' {
  declare module.exports: $Exports<'random/dist/distributions/uniform-int'>;
}
declare module 'random/dist/distributions/uniform.js' {
  declare module.exports: $Exports<'random/dist/distributions/uniform'>;
}
declare module 'random/dist/generators/function.js' {
  declare module.exports: $Exports<'random/dist/generators/function'>;
}
declare module 'random/dist/generators/math-random.js' {
  declare module.exports: $Exports<'random/dist/generators/math-random'>;
}
declare module 'random/dist/generators/xor128.js' {
  declare module.exports: $Exports<'random/dist/generators/xor128'>;
}
declare module 'random/dist/random.js' {
  declare module.exports: $Exports<'random/dist/random'>;
}
declare module 'random/dist/rng-factory.js' {
  declare module.exports: $Exports<'random/dist/rng-factory'>;
}
declare module 'random/dist/rng.js' {
  declare module.exports: $Exports<'random/dist/rng'>;
}
declare module 'random/index' {
  declare module.exports: $Exports<'random'>;
}
declare module 'random/index.js' {
  declare module.exports: $Exports<'random'>;
}
