// flow-typed signature: 9117638883f9547af89a4d923e7a7adf
// flow-typed version: <<STUB>>/resolve-swagger-refs_v^0.1.5/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve-swagger-refs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve-swagger-refs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resolve-swagger-refs/demo/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resolve-swagger-refs/demo/index.js' {
  declare module.exports: $Exports<'resolve-swagger-refs/demo/index'>;
}
declare module 'resolve-swagger-refs/index' {
  declare module.exports: $Exports<'resolve-swagger-refs'>;
}
declare module 'resolve-swagger-refs/index.js' {
  declare module.exports: $Exports<'resolve-swagger-refs'>;
}
