// flow-typed signature: 4888f4c1f6c80f9e474844ebfab0bf59
// flow-typed version: <<STUB>>/swagger-parser_v^6.0.2/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swagger-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swagger-parser/dist/swagger-parser' {
  declare module.exports: any;
}

declare module 'swagger-parser/dist/swagger-parser.min' {
  declare module.exports: any;
}

declare module 'swagger-parser/lib/index' {
  declare module.exports: any;
}

declare module 'swagger-parser/lib/options' {
  declare module.exports: any;
}

declare module 'swagger-parser/lib/util' {
  declare module.exports: any;
}

declare module 'swagger-parser/lib/validators/schema' {
  declare module.exports: any;
}

declare module 'swagger-parser/lib/validators/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swagger-parser/dist/swagger-parser.js' {
  declare module.exports: $Exports<'swagger-parser/dist/swagger-parser'>;
}
declare module 'swagger-parser/dist/swagger-parser.min.js' {
  declare module.exports: $Exports<'swagger-parser/dist/swagger-parser.min'>;
}
declare module 'swagger-parser/lib/index.js' {
  declare module.exports: $Exports<'swagger-parser/lib/index'>;
}
declare module 'swagger-parser/lib/options.js' {
  declare module.exports: $Exports<'swagger-parser/lib/options'>;
}
declare module 'swagger-parser/lib/util.js' {
  declare module.exports: $Exports<'swagger-parser/lib/util'>;
}
declare module 'swagger-parser/lib/validators/schema.js' {
  declare module.exports: $Exports<'swagger-parser/lib/validators/schema'>;
}
declare module 'swagger-parser/lib/validators/spec.js' {
  declare module.exports: $Exports<'swagger-parser/lib/validators/spec'>;
}
